[package]
name = "tensor-wgpu"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.14.2"
bytemuck = { version = "1.4", features = ["derive"]}
ndarray = "0.15.6"
num-traits = "0.2.15"